spring:
  application:
    name: suyu
#    关闭springboot图标
  main:
    banner-mode: off
#    配置数据库和连接池信息
  datasource:
    username: root
    password: lch
    url: jdbc:mysql://localhost:3306/suyu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    timeout: 5000
    store-type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 1
      lettuce:
        pool:
          enabled: true
          max-active: 8 #最大连接数
          max-idle: 8 #空闲时最多保留连接数
          min-idle: 0 #空闲时至少保持连接数
          max-wait: 100ms #和数据库连接时的最长等待时间

mybatis-plus:
  global-config:
    banner: off
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#   输出MP 执行的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置端口号，默认8080
server:
  port: 8080
  servlet:
    context-path: /api
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '素遇'
      paths-to-match: '/**'
      packages-to-scan: com.lch.suyu.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
